### ISSUE TITLE
Unable to find type [AngleSharp.Html.Parser.HtmlParser]

### ISSUE THREAD

**Issue by casper392945** [EvotecIT/PSParseHTML#6]
File: PowerShell/Modules/PSParseHTML/0.0.24/PSParseHTML.psm1
Line 772

    Begin {
        # Initialize the parser
        $HTMLParser = [AngleSharp.Html.Parser.HtmlParser]::new()
    }

Unable to find type [AngleSharp.Html.Parser.HtmlParser]

**Comment by PrzemyslawKlys** [comment]
I would appreciate if you spend a few seconds more on reporting issues with a bit more details. Thank you. The problem should be fixed now.

**Comment by casper392945** [comment]
Everything worked, thanks for solving the problem.
